# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    develop:
      - step:
          script: # Modify the commands below to build your repository.
      #    - dotnet restore
      #   - dotnet build
       #   - cd app && npm install
       #   - npm test
        #  - git config --global user.email "piepline@bitbucket.com"
        #  - git config --global user.name "Bitbucket Pipeline"
        #  - git fetch https://EP_AZURE_DEPLOY:$EP_AZURE_DEPLOY_PWD@imescheduletool.scm.azurewebsites.net:443/imescheduletool.git
        #  - npm run publish
#          - dotnet test TestName
    master:
          - step:
              script: # Modify the commands below to build your repository.
             ##- dotnet build
          #    - cd app && npm install
          #    - npm test
          #    - git config --global user.email "piepline@bitbucket.com"
          #    - git config --global user.name "Bitbucket Pipeline"
            #  - npm run publish:demo